---
abstract: 'The configuration file of Sledge can be written by using YAML.'
author:
  - 'KAN Fushihara <kan at mobilefactory.jp>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.32
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sledge-Config-YAML
no_index:
  directory:
    - inc
    - t
requires:
  File::Slurp: 0
  Filter::Util::Call: 0
  YAML::Syck: 1.07
version: 0.09
