abstract: The configuration file of Sledge can be written by using YAML.
author: KAN Fushihara <kan at mobilefactory.jp>
build_requires: 
  Test::More: 0.32
distribution_type: module
generated_by: Module::Install version 0.64
license: unknown
name: Sledge-Config-YAML
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::Visitor::Callback: 0
  YAML: 0.39
version: 0.06
